## ------------------------------------------------------------------------------------------------------------------ ##
## CONFIG DEMO: config.demo.yaml                                                                                      ##
##                                                                                                                    ##
## Author: Uberate                                                                                                    ##
## Email: <ubserate@gmail.com>                                                                                        ##
##                                                                                                                    ##
## This output show the config demo of application.                                                                   ##
## ------------------------------------------------------------------------------------------------------------------ ##

# group_filters 
# The group_filters will try to group the res of this filters by elements. 
#
group_filters:
  - key: "科技"
    values:
      - "科技"
      - "技术"
      - "手机"
      - "智能"
      - "图灵"
      - "计算机"
      - "显卡"
      - "GPU"
      - "基因"
      - "深度学习"
      - "神经网络"
  - key: "医疗"
    values:
      - "药" # 药 中药 西药 药物 药品
      - "病" # 病 病毒 病原体
      - "癌症"
      - "治愈"
      - "治疗"
      - "基因"
      - "健康"
      - "长寿"
      - "寿命"
      - "年龄"
      - "医" # 医 医院 医学院 医学生 医生
  - key: "金融"
    values:
      - "股份"
      - "利润"
      - "投资"
      - "营收"
      - "亏损"
  - key: "汽车"
    values:
      - "汽车"
      - "车企"
      - "车展"
      - "新能源"
      - "跑车" ## 类型
      - "房车"
      - "轿跑"
      - "宝马" ## 车企，无序
      - "保时捷"
      - "宾利"
      - "五菱宏光"
      - "比亚迪"
      - "特斯拉"
      - "大众"
      - "一汽大众"
  - key: "影视"
    values:
      - "漫威"
      - "DC"
      - "电影"
      - "电视剧"
      - "演员"
      - "歌曲"
      - "片尾曲"
      - "片头曲"
      - "插曲"
      - "" # TODO
### If the article body or title has this key word, these news will group to technology group.
### If some article has more than one group key word in different filters, these news will group to these groups.

# disable_getters
# To disable some getters.
#
# If you want to get all getters from the application, start the application with: '-s' or '--show-getters'
disable_getters: [ ]

run_cron: "@every 1m"

getters:
  - kind: sina
    version: v1
    name: test