name: go build version

on:
  push:
    tags:
      - v**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: set up go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: code test
      run: go test ./...

    - name: build linux-amd64
      run: GOOS=linux GOARCH=amd64 go build -o ./output/darwin-amd64-newsdumper cmd/bin/main.go

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body_path: output/
        draft: false
        prerelease: false
